application: instantyaml
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: media/images/favicon.ico
  upload: media/images/favicon.ico

- url: /robots.txt
  static_files: media/images/robots.txt
  upload: media/images/robots.txt
  
- url: /media/css
  static_dir: media/css
  
- url: /admin/
  script: admin.py
  login: admin
  
- url: /.*
  script: yamler.py
  


